# -*- coding: utf-8 -*-
"""A-A2-28 ---Practical 5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oS8MqSKOBV8O65OSy4slB5cOcIw0VTH-

# Tanishq Ikhar
# A
# A2- 28
# Practical 5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import (train_test_split,GridSearchCV,cross_val_score,StratifiedKFold)
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import(accuracy_score, precision_score,recall_score,f1_score,confusion_matrix,classification_report)

import warnings
warnings.filterwarnings("ignore")
sns.set_theme(style="whitegrid")

df = pd.read_csv("diabetes.csv")
print("shape:",df.shape)
df.head()

zero_columns = ["Glucose","BloodPressure","SkinThickness","Insulin","BMI"]
zero_counts = (df[zero_columns] == 0).sum()
print("Zero Counts:")
print(zero_counts)

df_clean = df.copy()
df_clean[zero_columns] = df_clean[zero_columns].replace(0,np.nan)
print("Missing values after repalcing inavlid zeros: ")
print(df_clean.isnull().sum())

for col in zero_columns:
    df_clean[col].fillna(df_clean[col].median(), inplace=True)

print("Missing values after imputation:")
print(df_clean.isnull().sum())

X = df_clean.drop("Outcome", axis=1)
y = df_clean["Outcome"]

print("X shape:",X.shape)
print("y shape:",y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y)

print("X_train shape:",X_train.shape[0])

print("X_test shape:",X_test.shape[0])

print("Training distribution:")
print(y_train.value_counts(normalize = True))
print("Testing distribution:")
print(y_test.value_counts(normalize=True))

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

scaler.fit_transform(X_test)

scaler.transform(X_test)

comparison = pd.DataFrame({"Original Mean ":X_train.mean(),"Original Std":X_train.std(),"Scaled Mean ":X_train_scaled.mean(axis=0),"Scaled Std":X_train_scaled.std(axis=0)})
display(comparison)

K = 5

knn = KNeighborsClassifier(n_neighbors=K)
knn.fit(X_train_scaled,y_train)

y_pred = knn.predict(X_test_scaled)
print("Prediction:")
print(y_pred[:20])

y_proba = knn.predict_proba(X_test_scaled)
print("Prediction probabilities:")
print(y_proba[:20])

accuracy = accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy)
precision = precision_score(y_test,y_pred)
print("Precision:",precision)
recall = recall_score(y_test,y_pred)
print("Recall:",recall)
f1 = f1_score(y_test,y_pred)
print("F1 Score:",f1)

print(classification_report(y_test,y_pred,target_names=["No Diabetes","Diabetes"]))

cm = confusion_matrix(y_test,y_pred)
print(cm)

plt.figure(figsize=(8,6))
sns.heatmap(cm,annot=True,fmt="d",cmap="Blues",xticklabels=["No Diabetes","Diabetes"],yticklabels=["No Diabetes","Diabetes"])
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

k_values = range(1,31)

train_accuracy = []
test_accuracy = []

for k in k_values:
  model = KNeighborsClassifier(n_neighbors=k)
  model.fit(X_train_scaled,y_train)
  train_accuracy.append(model.score(X_train_scaled,y_train))
  test_accuracy.append(model.score(X_test_scaled,y_test))

plt.figure(figsize=(10,6))
plt.plot(k_values,train_accuracy,marker ="o",label="Training Accuracy")
plt.plot(k_values,test_accuracy,marker="s",label="Testing Accuracy")
plt.xlabel("K Values")
plt.ylabel("Accuracy")
plt.title("K vs KNN-Accuracy")
plt.legend()
plt.show()

best_k_accuracy  = k_values[np.argmax(test_accuracy)]

best_accuracy = max(test_accuracy)
print("Best K value:",best_k_accuracy)
print("Best Accuracy:",best_accuracy)

cv = StratifiedKFold(n_splits=5,shuffle=True,random_state=42)
cv_scores = []
for k in range(1,31):
  model = KNeighborsClassifier(n_neighbors=k)
  scores = cross_val_score(model,X_train_scaled,y_train,cv=cv,scoring="accuracy")
  cv_scores.append(scores.mean())

best_k_cv = np.argmax(cv_scores) + 1

print("Best K value based on Cross Validation:",best_k_cv)
print("Best CV accuracy based on Cross Validation:",max(cv_scores))

param_grid = {"n_neighbors":list(range(3,31,2)),"weights":["uniform","distance"],"metric":["euclidean","manhattan","minkowski"],"p":[1,2]}
grid_search = GridSearchCV(KNeighborsClassifier(),param_grid,cv=5,scoring="accuracy",n_jobs=-1)
grid_search.fit(X_train_scaled,y_train)

print("Best parameters:", grid_search.best_params_)
print("Best cross-validation score:", grid_search.best_score_)

best_knn = grid_search.best_estimator_
print(best_knn)

final_pred = best_knn.predict(X_test_scaled)
final_prob = best_knn.predict_proba(X_test_scaled)[:,1]

final_accuracy = accuracy_score(y_test,final_pred)
final_precision = precision_score(y_test,final_pred)
final_recall = recall_score(y_test,final_pred)
final_f1 = f1_score(y_test,final_pred)

print("Final Accuracy:",final_accuracy)
print("Final Precision:",final_precision)
print("Final Recall:",final_recall)
print("Final F1 Score:",final_f1)

